In [146]:
import numpy as np
r = np.random.randint(1, 40)
r

22

In [147]:
c = np.random.randint(1, 50)
c

31

In [148]:
np_arry = np.array(np.random.randint(1, 100, (r * c)))
sized = np_arry.reshape(r, c)
sized

array([[46, 53, 72,  3, 22, 75, 89, 70, 87,  7, 33, 49, 29, 79, 29, 95,
        19, 76, 62, 10, 63, 11, 79, 16, 89, 29, 53, 26, 93, 25, 16],
       [26, 37, 38, 25, 40, 85, 64, 72, 29, 69, 41, 74,  5, 40,  9, 65,
        29, 79, 37, 67,  9, 18, 26, 81, 10, 35, 24, 45, 88, 95,  2],
       [60,  7, 95, 81, 51, 91,  1, 86, 37, 90, 57, 35, 85, 50, 31, 60,
        21, 56, 19, 84, 84, 20, 68, 49, 72,  8, 41, 25, 66, 76, 62],
       [85, 52,  6, 17, 32, 37, 23, 35, 51, 16, 49, 14, 53, 98, 93, 69,
        84, 88, 99, 55,  7, 81, 59, 69, 82, 90, 37, 19, 98, 51, 27],
       [17, 93, 91, 37, 83, 71,  6, 54, 11, 46, 79, 18, 71, 26, 69, 23,
        68, 23, 62, 79, 73, 48, 15, 49, 88, 37, 10, 35, 10, 48, 15],
       [82,  1,  8, 53, 11, 66, 69, 56, 97, 57,  5, 57, 81, 41, 26, 48,
        93,  3, 37, 11, 13, 72, 92, 89, 64, 44, 68, 10, 73, 74, 53],
       [39, 46,  3, 58, 46, 20, 48, 79, 91, 87, 45, 21, 30, 22, 34, 73,
        77, 93, 18, 94, 32, 69, 11, 28, 93, 58, 20, 78, 38, 18, 24],
       [ 8, 6

In [131]:
sized[2]

array([43, 99, 51, 41, 14, 25, 77, 41, 28, 12, 45, 51, 88, 96, 16, 41, 82,
       55, 41, 67, 59, 79, 28,  5, 99, 72, 11, 16, 80,  2])

In [134]:
sized[:,2]

array([37, 67, 51, 91, 83, 20, 60, 73, 15, 75, 42, 84, 69, 54, 14, 12, 97,
       27, 38,  8, 86, 47, 56, 61, 62, 89, 55, 54, 91, 76, 79, 61, 79, 34,
       66,  3, 20, 94, 22, 78, 25, 45, 43, 41, 59, 89, 90,  7, 36, 93, 98,
       16, 19, 47, 91, 78,  1, 37,  9, 96])

In [173]:
last_row = sized[-1] = 7
last_row
sized

array([[  46,   53,   72,    3,   22,   75,   89,   70,   87,    7,   33,
          49,   29,   79,   29,   95,   19,   76,   62,   10,   63,   11,
          79,   16,   89,   29,   53,   26,   93,   25, 2865],
       [  26,   37,   38,   25,   40,   85,   64,   72,   29,   69,   41,
          74,    5,   40,    9,   65,   29,   79,   37,   67,    9,   18,
          26,   81,   10,   35,   24,   45,   88,   95, 2865],
       [  60,    7,   95,   81,   51,   91,    1,   86,   37,   90,   57,
          35,   85,   50,   31,   60,   21,   56,   19,   84,   84,   20,
          68,   49,   72,    8,   41,   25,   66,   76, 2865],
       [  85,   52,    6,   17,   32,   37,   23,   35,   51,   16,   49,
          14,   53,   98,   93,   69,   84,   88,   99,   55,    7,   81,
          59,   69,   82,   90,   37,   19,   98,   51, 2865],
       [  17,   93,   91,   37,   83,   71,    6,   54,   11,   46,   79,
          18,   71,   26,   69,   23,   68,   23,   62,   79,   73,   48,
        

In [169]:
sum_col_1 = np.sum(sized[0])
sum_col_2 = np.sum(sized[1])

last_row_item = sized[:,-1][:] = sum_col_1 + sum_col_2
last_row_item
sized

array([[  46,   53,   72,    3,   22,   75,   89,   70,   87,    7,   33,
          49,   29,   79,   29,   95,   19,   76,   62,   10,   63,   11,
          79,   16,   89,   29,   53,   26,   93,   25, 2865],
       [  26,   37,   38,   25,   40,   85,   64,   72,   29,   69,   41,
          74,    5,   40,    9,   65,   29,   79,   37,   67,    9,   18,
          26,   81,   10,   35,   24,   45,   88,   95, 2865],
       [  60,    7,   95,   81,   51,   91,    1,   86,   37,   90,   57,
          35,   85,   50,   31,   60,   21,   56,   19,   84,   84,   20,
          68,   49,   72,    8,   41,   25,   66,   76, 2865],
       [  85,   52,    6,   17,   32,   37,   23,   35,   51,   16,   49,
          14,   53,   98,   93,   69,   84,   88,   99,   55,    7,   81,
          59,   69,   82,   90,   37,   19,   98,   51, 2865],
       [  17,   93,   91,   37,   83,   71,    6,   54,   11,   46,   79,
          18,   71,   26,   69,   23,   68,   23,   62,   79,   73,   48,
        