In [13]:
arry = np.arange(1, 101)
arry

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
import numpy as np
np.arange(start = 6, stop = 100, step = 4)

array([ 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70,
       74, 78, 82, 86, 90, 94, 98])

In [26]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a = a[~np.isnan(a)]
a


array([1., 2., 3., 5., 6., 7.])

In [40]:
next_arry = np.random.randint(1, 100, (5,6))
sum(next_arry[0])
sum(next_arry[1])
sum(next_arry[3])
sum(next_arry[4])
next_arry


array([[73, 16,  7, 63, 86, 28],
       [15, 74, 64, 73, 23, 28],
       [78, 36, 21, 72, 25, 45],
       [61, 78, 46, 94, 24, 34],
       [80, 66, 60,  1, 55, 47]])

In [2]:
import pandas as pd
import numpy as np
series = pd.Series(np.take(list('abcdefghijklmnop'), np.random.randint(16, size=500)))
series

0      l
1      i
2      i
3      o
4      n
      ..
495    e
496    m
497    c
498    k
499    k
Length: 500, dtype: object

In [9]:
import pandas as pd
from dateutil.parser import parse
series = pd.Series(['01 Jan 2020', '10-19-2020', '20150303', '2013/04/04', '2012-05-05', '2013-06-06T12:20'])
print("Original Series:")
print(series)
series = series.map(lambda x: parse(x))
print("Day of month:")
print(series.dt.day.tolist())
print("Day of year:")
print(series.dt.dayofyear.tolist())
print("Week number:")
print(series.dt.isocalendar().week)
print("Day of week:")
print(series.dt.weekday_name.tolist())

Original Series:
0         01 Jan 2020
1          10-19-2020
2            20150303
3          2013/04/04
4          2012-05-05
5    2013-06-06T12:20
dtype: object
Day of month:
[1, 19, 3, 4, 5, 6]
Day of year:
[1, 293, 62, 94, 126, 157]
Week number:
0     1
1    43
2    10
3    14
4    18
5    23
Name: week, dtype: UInt32
Day of week:


AttributeError: 'DatetimeProperties' object has no attribute 'weekday_name'

In [13]:
c = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
c
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             87 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

In [17]:
 c.rename(columns = {'Type': "TypeOfCar"})

Manufacturer    Model TypeOfCar  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra     Small       12.9   15.9       18.8      25.0   
1           NaN   Legend   Midsize       29.2   33.9       38.7      18.0   
2          Audi       90   Compact       25.9   29.1       32.3      20.0   
3          Audi      100   Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i   Midsize        NaN   30.0        NaN      22.0   
..          ...      ...       ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan       Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat   Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado    Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240   Compact       21.8   22.7       23.5      21.0   
92          NaN      850   Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [23]:
c.isnull()
new_data = c.dropna(axis = 0, how ='any') 
new_data

print("Old data frame length:", len(c))
print("New data frame length:", len(new_data)) 
print("Number of rows with at least 1 NA value: ", (len(c)-len(new_data)))

Old data frame length: 93
New data frame length: 20
Number of rows with at least 1 NA value:  73


In [31]:
del c['Length']
del c['EngineSize']


KeyError: 'EngineSize'

In [32]:
c

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Fuel.tank.capacity  \
0          31.0                None      Front  ...               13.2   
1          25.0  Driver & Passenger      Front  ...               18.0   
2          26.0         Driver only      Front  ...               16.9   
3          26.0  Driver & Passenger        NaN  ...               21.1   
4          30.0                 NaN       Rear  ...               21.1   
..          ...                 ...        ...  ...                ...   
88         21.0                None      Front  ...               21.1   
89         30.0                None      Front  ...               18.5   
90         25.0                None      Front  ...               18.5   
91         28.0         Driver only       Rear  ...               15.8   
92         28.0  Driver & Passenger      Front  ...               19.3   

    Passengers  Wheelbase  Width Turn.circle  Rear.seat.room  Luggage.room  \
0          5.0      102.0   68.0        37.0            26.5           NaN   
1          5.0      115.0   71.0        38.0            30.0          15.0   
2          5.0      102.0   67.0        37.0            28.0          14.0   
3          6.0      106.0    NaN        37.0            31.0          17.0   
4          4.0      109.0   69.0        39.0            27.0          13.0   
..         ...        ...    ...         ...             ...           ...   
88         7.0      115.0   72.0        38.0            34.0           NaN   
89         5.0      103.0   67.0        35.0            31.5          14.0   
90         4.0       97.0   66.0        36.0            26.0          15.0   
91         5.0      104.0   67.0        37.0            29.5          14.0   
92         5.0      105.0   69.0        38.0            30.0          15.0   

    Weight   Origin                Make  
0   2705.0  non-USA       Acura Integra  
1   3560.0  non-USA        Acura Legend  
2   3375.0  non-USA             Audi 90  
3   3405.0  non-USA            Audi 100  
4   3640.0  non-USA            BMW 535i  
..     ...      ...                 ...  
88  3960.0      NaN  Volkswagen Eurovan  
89  2985.0  non-USA   Volkswagen Passat  
90  2810.0  non-USA  Volkswagen Corrado  
91  2985.0  non-USA           Volvo 240  
92  3245.0  non-USA           Volvo 850  

[93 rows x 25 columns]

In [45]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})
df1

fruit  weight  price
0   apple    high      1
1  banana  medium      3
2  orange     low      8
3   apple    high      2
4  banana  medium      4
5  orange     low      6
6   apple    high     11
7  banana  medium     10
8  orange     low      7

In [46]:
df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
df2

pazham  kilo  price
0   apple  high     11
1  orange   low     12
2    pine  high      4
3   apple   low      8
4  orange  high      6
5    pine   low      0

In [47]:
df_merge_col = pd.merge(df1, df2)
df_merge_col

fruit  weight  price  pazham  kilo
0  orange     low      8   apple   low
1  banana  medium      4    pine  high
2  orange     low      6  orange  high
3   apple    high     11   apple  high

In [62]:
df = pd.DataFrame(["STD,City\tState",
"33,Kolkata\tWest Bengal",
"44,Chennai\tTamil Nadu",
"40,Hyderabad\tTelengana",
"80,Bangalore\tKarnataka"], columns=['row'])
df

row
0          STD,City\tState
1  33,Kolkata\tWest Bengal
2   44,Chennai\tTamil Nadu
3  40,Hyderabad\tTelengana
4  80,Bangalore\tKarnataka

In [67]:
out = pd.DataFrame(df.row.str.split(' ',2).tolist(),columns=['STD','City','State'])
out.drop(index=0,inplace=True)

ValueError: 3 columns passed, passed data had 2 columns

In [65]:
out

STD City         State
1     33,Kolkat        West Bengal
2    44,Chennai         Tamil Nadu
3  40,Hyderabad          Telengana
4  80,Bangalore          Karnataka